# Generated by Django 6.1.2 on 2026-10-07 22:25

import django.db.models.deletion
import django_mongodb_backend.fields
import django_mongodb_backend.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_id', django_mongodb_backend.fields.ObjectIdField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_method', models.CharField(default='equal', max_length=20)),
                ('participants', django_mongodb_backend.fields.EmbeddedModelArrayField(default=list, embedded_model='subscriptions.participant', max_size=20)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sharing', django_mongodb_backend.fields.EmbeddedModelField(blank=True, embedded_model='subscriptions.sharing', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
                'indexes': [django_mongodb_backend.indexes.EmbeddedFieldIndex(fields=['sharing.participants.email'], name='subs_participant_email')],
            },
        ),
    ]
